title: IDLE Press Arcade
description: IDLE Press Arcade documentation.
theme: just-the-docs

url: https://rocket5.ca
baseurl: /idlepressarcade

# Configure paths for assets
relative_links:
  enabled: true
  collections: true

callouts:
  warning:
    title: Warning
    color: red
  info:
    title: Info
    color: blue
  tip:
    title: Tip
    color: purple
  note:
    title: Note
    color: yellow
  new:
    title: New
    color: green

aux_links:
  Rocket 5 Studios: https://rocket5.ca

# Color scheme supports "light" (default) and "dark"
#color_scheme: dark

# External navigation links
nav_external_links:
  - title: Just the Docs on GitHub
    url: https://github.com/just-the-docs/just-the-docs
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: false # set to true to open this link in a new tab - defaults to false